### ISSUE TITLE
Please, publish to hackage

### ISSUE THREAD

**Issue by safinaskar** [subttle/regular#12]
Hi. Thanks for good lib. Please, publish it to Hackage, I want to use it

**Comment by subttle** [comment]
Hi @safinaskar, thank you so much for the kind words! I do have publishing-to-Hackage on my list of things to do; however, it is low priority for me at the moment (but there are plenty of fast/practical Regular Expression, etc. libraries which already exist on Hackage, if that's what you need). While I am remarkably proud of the code I have so far, I still have a lot more I need to do before the code reaches its real potential and is ready to be released. For example some reorganization/optimization tasks. I apologize if that is an inconvenience! Thank you for your understanding.

**Comment by safinaskar** [comment]
> but there are plenty of fast/practical Regular Expression, etc. libraries which already exist on Hackage

They are not for me. I want library for exactly that task you are aiming for: i. e. working with regular languages, in particular checking whether two given regular languages have non-empty intersection.

My original task is here: https://mail.haskell.org/pipermail/haskell-cafe/2021-January/133275.html . I will probably create combinator library, which will allow one to embed something similar to Augeas-like ( http://augeas.net ) language description directly to Haskell code. And I need some regular language library for this. ( Augeas uses libfa [ http://augeas.net/libfa/index.html ] for this task, but, unfortunately, libfa is written in C and has no Haskell bindings).

So I created this bug report. Since this bug report was created, it seems I found library I want on Hackage: http://hackage.haskell.org/package/kleene . So, it seems, I will use it. I hope you are not offended.

Also, I found this lib: https://github.com/cacay/regexp , but it is not published on Hackage, too

And these: http://hackage.haskell.org/package/regex-deriv , http://hackage.haskell.org/package/regex-pderiv and http://hackage.haskell.org/package/antimirov . They will not go for me, I don't remember why.

And this: https://hackage.haskell.org/package/regexpr-symbolic . Hackage was not able to build it

**Comment by subttle** [comment]
> They are not for me. I want library for exactly that task you are aiming for: i. e. working with regular languages, in particular checking whether two given regular languages have non-empty intersection.

If you are by chance using `stack` (which I don't necessarily recommend, I've heard good things about Nix) then one may add dependencies not on hackage by editing the `stack.yaml` file, to then pull the code directly from a github repository. I even do this in this particular repository when I pull in `EasyTest` from Unisonweb. It looks like this:
```yaml
- github: unisonweb/unison
  commit: 3f4e8a450a1bf7e370576709f0601836aabc6d79
  subdirs:
    - yaks/easytest
```

> So I created this bug report. Since this bug report was created, it seems I found library I want on Hackage: http://hackage.haskell.org/package/kleene . So, it seems, I will use it. I hope you are not offended.

No offense taken at all, @phadej writes some of the best code out there (my library depends on phadej's wonderful `fin` package)! I will close this ticket for now because it seems you have what you need but please feel free to reopen it as you see fit. Take care!
